---
- hosts: localhost
  become: true 
  tasks:
  - name: Install apache httpd  (state=present is optional)
    apt:
      name: 
      - git
      - apache2

- hosts: CSR1kv
  gather_facts: true
  roles:
    - save_configs
    
